// Test generated by RoostGPT for test ReactTest1 using AI Type Open AI and AI Model gpt-4-1106-preview

// Importing the required testing utilities and the data
import data from './Data/data';

describe('Room Data', () => {
  test('Data is an array', () => {
    expect(Array.isArray(data)).toBe(true);
  });

  test('Data array contains room objects', () => {
    // We assume that each room should at least have an id and a name
    data.forEach(room => {
      expect(room).toHaveProperty('sys');
      expect(room.sys).toHaveProperty('id');
      expect(room).toHaveProperty('fields');
      expect(room.fields).toHaveProperty('name');
    });
  });

  test('Room objects have the required fields with correct types', () => {
    data.forEach(room => {
      const { id } = room.sys;
      const { name, slug, type, price } = room.fields;

      expect(typeof id).toBe('string');
      expect(typeof name).toBe('string');
      expect(typeof slug).toBe('string');
      expect(typeof type).toBe('string');
      expect(typeof price).toBe('number');
    });
  });

  // Add more tests below for each specific requirement and edge case.
  // For example:
  // - Verify the uniqueness of each room's slug.
  // - Ensure no room has a price of zero or a negative value.
  // - Confirm all expected image assets are present and loaded correctly.
});

