// Test generated by RoostGPT for test ReactTest1 using AI Type Open AI and AI Model gpt-4-1106-preview

import { data } from './path/to/data';

describe('data.js – Room Data', () => {
    test('should export an array', () => {
        expect(data).toBeInstanceOf(Array);
    });

    test('should contain room objects with required fields', () => {
        data.forEach(room => {
            expect(room).toHaveProperty('sys');
            expect(room.sys).toHaveProperty('id');
            expect(room).toHaveProperty('fields');
            expect(room.fields).toHaveProperty('name');
            expect(room.fields).toHaveProperty('slug');
            expect(room.fields).toHaveProperty('type');
            expect(room.fields).toHaveProperty('price');
            // ... additional required fields
        });
    });

    test('should have non-empty id and slug fields for all rooms', () => {
        data.forEach(room => {
            expect(room.sys.id).toBeTruthy();
            expect(room.fields.slug).toBeTruthy();
        });
    });

    // Additional tests like checking if the price is a number, if the images are correctly imported, etc.
});

