// Test generated by RoostGPT for test ReactTest1 using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render, screen } from '@testing-library/react';
import Hero from '../../src/Components/Hero/Hero';

describe('Hero Component', () => {
  // Test case 1: It should render with default props
  test('renders with default props', () => {
    render(<Hero />);
    const headerElement = screen.getByRole('banner');
    expect(headerElement).toBeInTheDocument();
    expect(headerElement).toHaveClass('defaultHero');
  });

  // Test case 2: It should apply custom class via props
  test('applies custom class via props', () => {
    const customClass = 'customHero';
    render(<Hero hero={customClass} />);
    const headerElement = screen.getByRole('banner');
    expect(headerElement).toHaveClass(customClass);
  });

  // Feel free to add more test cases for different scenarios
  // For example: Rendering with children, testing for absence of a class, etc.
});

