// Test generated by RoostGPT for test ReactTest1 using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { BrowserRouter as Router } from 'react-router-dom';
import { render, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Navbar from './Navbar';

describe('Navbar Component', () => {
  // Test case 1: Component renders without crashing
  test('renders without crashing', () => {
    render(
      <Router>
        <Navbar />
      </Router>
    );
  });

  // Test case 2: Toggle button correctly alters the state
  test('toggle button changes visibility of navigation links', () => {
    const { getByRole, queryByTestId } = render(
      <Router>
        <Navbar />
      </Router>
    );
    const button = getByRole('button');
    fireEvent.click(button);
    expect(queryByTestId('nav-links')).toHaveClass('show-nav');
  });

  // Test case 3: Navigation links are not visible when isOpen is false
  test('navigation links are not visible when menu is closed', () => {
    const { queryByTestId } = render(
      <Router>
        <Navbar />
      </Router>
    );
    expect(queryByTestId('nav-links')).not.toHaveClass('show-nav');
  });

  // Test case 4: Navigation links are visible when isOpen is true
  test('navigation links are visible when menu is open', () => {
    const { getByRole, queryByTestId } = render(
      <Router>
        <Navbar />
      </Router>
    );
    const button = getByRole('button');
    fireEvent.click(button);
    expect(queryByTestId('nav-links')).toHaveClass('show-nav');
  });

  // Test case 5: Navigation contains links to the Home and Rooms routes
  test('contains links to Home and Rooms', () => {
    const { getByText } = render(
      <Router>
        <Navbar />
      </Router>
    );
    expect(getByText('Home')).toBeInTheDocument();
    expect(getByText('Rooms')).toBeInTheDocument();
  });
});

