// Test generated by RoostGPT for test ReactTest1 using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render, cleanup } from '@testing-library/react';
import RoomList from './RoomsList'; // Adjust the relative path as needed

// Clean up after each test
afterEach(cleanup);

describe('RoomList component', () => {
  test('displays a message when no rooms are available', () => {
    const { getByText } = render(<RoomList rooms={[]} />);
    expect(getByText('unfortunately no rooms matched your search parameters')).toBeInTheDocument();
  });

  test('displays a list of rooms when rooms are available', () => {
    const rooms = [{ id: 1, ...roomData }, { id: 2, ...roomData }]; // Replace ...roomData with actual room data
    const { getByText } = render(<RoomList rooms={rooms} />);
    expect(getByText(/* room name or identifier */)).toBeInTheDocument();
  });
});

