// Test generated by RoostGPT for test ReactTest1 using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render } from '@testing-library/react';
import StyledHero from './StyledHero';
import defaultImg from './../../assets/img/jpeg/room-1.jpeg';

describe('StyledHero Component', () => {
  test('renders with default background image when no img prop is provided', () => {
    const { getByTestId } = render(<StyledHero />);
    const heroElement = getByTestId('styled-hero');
    expect(heroElement).toHaveStyle(`background-image: url(${defaultImg})`);
  });

  test('renders with the provided background image prop', () => {
    const testImg = 'path/to/test/image.jpg';
    const { getByTestId } = render(<StyledHero img={testImg} />);
    const heroElement = getByTestId('styled-hero');
    expect(heroElement).toHaveStyle(`background-image: url(${testImg})`);
  });
});

